version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ryzen5600
      MYSQL_DATABASE: ups_monitoring_dev
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ups_monitoring_dev?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ryzen5600
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: