spring:
  application:
    name: ups-monitoring-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ryzen5600
    url: JDBC:mysql://localhost:3306/ups_monitoring_dev?useSSL=false&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    Hikari:
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  server:
    address: 0.0.0.0
    port: 8080